services:
  - type: web
    name: myshop2
    env: python
    rootDir: myshop2
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn myshop.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: myshop2-db
          property: connectionString

databases:
  - name: myshop2-db
    databaseName: myshop2
    user: myshop2 